/*----------------------------------------------------------------------------------*/
/* Product:            Visual Data Mining and Machine Learning                      */
/* Release Version:    V2021.1.3                                                    */
/* Component Version:  V2021.1.3                                                    */
/* CAS Version:        V.04.00M0P07182021                                           */
/* SAS Version:        V.04.00M0P071821                                             */
/* Site Number:        70180938                                                     */
/* Host:               sas-cas-server-default-client                                */
/* Encoding:           utf-8                                                        */
/* Java Encoding:      UTF8                                                         */
/* Locale:             en_US                                                        */
/* Project GUID:       e3479afc-d396-42ae-a787-b042adc0cb8d                         */
/* Node GUID:          e6983492-884b-4dde-a4e1-82eaba589144                         */
/* Node Id:            DNGOB3MOZDU4DFX9F9860I81W                                    */
/* Algorithm:          Gradient Boosting                                            */
/* Generated by:       Frederik.Vandenberghe@sas.com                                */
/* Date:               05AUG2021:12:46:16                                           */
/*----------------------------------------------------------------------------------*/
package MS_e6983492884b4ddea4e182eaba589144_05AUG2021124616485 / overwrite=yes;
   dcl package score _DNGOB3MOZDU4DFX9F9860I81W();
   dcl double "x_axis_deg_s";
   dcl double "x_axis_g";
   dcl double "y_axis_deg_s";
   dcl double "y_axis_g";
   dcl double "z_axis_deg_s";
   dcl double "z_axis_g";
   dcl nchar(6) "Eyes";
   dcl nchar(3) "Support";
   dcl double "P_TARGET1" having label n'Predicted: TARGET=1';
   dcl double "P_TARGET0" having label n'Predicted: TARGET=0';
   dcl nchar(32) "I_TARGET" having label n'Into: TARGET';
   dcl nchar(4) "_WARN_" having label n'Warnings';
   dcl double EM_EVENTPROBABILITY;
   dcl nchar(12) EM_CLASSIFICATION;
   dcl double EM_PROBABILITY;
   varlist allvars [_all_];
 
    
   method init();
      _DNGOB3MOZDU4DFX9F9860I81W.setvars(allvars);
      _DNGOB3MOZDU4DFX9F9860I81W.setkey(n'B865177510CB3AB4F5B36AB6261D96EF0D7870A4');
   end;
    
   method post_DNGOB3MOZDU4DFX9F9860I81W();
      dcl double _P_;
       
      if "P_TARGET0" = . then "P_TARGET0" = 0.5;
      if "P_TARGET1" = . then "P_TARGET1" = 0.5;
      if MISSING("I_TARGET") then do ;
      _P_ = 0.0;
      if "P_TARGET1" > _P_ then do ;
      _P_ = "P_TARGET1";
      "I_TARGET" = '           1';
      end;
      if "P_TARGET0" > _P_ then do ;
      _P_ = "P_TARGET0";
      "I_TARGET" = '           0';
      end;
      end;
      EM_EVENTPROBABILITY = "P_TARGET1";
      EM_CLASSIFICATION = "I_TARGET";
      EM_PROBABILITY = MAX("P_TARGET1", "P_TARGET0");
    
   end;
    
 
   method score(
      varchar(6) "Eyes",
      varchar(3) "Support",
      double "x_axis_deg_s",
      double "x_axis_g",
      double "y_axis_deg_s",
      double "y_axis_g",
      double "z_axis_deg_s",
      double "z_axis_g",
      IN_OUT char(12) "EM_CLASSIFICATION",
      IN_OUT double "EM_EVENTPROBABILITY",
      IN_OUT double "EM_PROBABILITY",
      IN_OUT char(32) "I_TARGET",
      IN_OUT double "P_TARGET0",
      IN_OUT double "P_TARGET1",
      IN_OUT double "_P_",
      IN_OUT char(4) "_WARN_"
   );
      this."Eyes"= "Eyes";
      this."Support"= "Support";
      this."x_axis_deg_s"= "x_axis_deg_s";
      this."x_axis_g"= "x_axis_g";
      this."y_axis_deg_s"= "y_axis_deg_s";
      this."y_axis_g"= "y_axis_g";
      this."z_axis_deg_s"= "z_axis_deg_s";
      this."z_axis_g"= "z_axis_g";
 
      _DNGOB3MOZDU4DFX9F9860I81W.scoreRecord();
      post_DNGOB3MOZDU4DFX9F9860I81W();
 
      "EM_CLASSIFICATION"= this."EM_CLASSIFICATION";
      "EM_EVENTPROBABILITY"= this."EM_EVENTPROBABILITY";
      "EM_PROBABILITY"= this."EM_PROBABILITY";
      "I_TARGET"= this."I_TARGET";
      "P_TARGET0"= this."P_TARGET0";
      "P_TARGET1"= this."P_TARGET1";
      "_P_"= this."_P_";
      "_WARN_"= this."_WARN_";
   end;
 
 
   method predictedscore(
      varchar(6) "Eyes",
      varchar(3) "Support",
      double "x_axis_deg_s",
      double "x_axis_g",
      double "y_axis_deg_s",
      double "y_axis_g",
      double "z_axis_deg_s",
      double "z_axis_g",
      IN_OUT char(12) "EM_CLASSIFICATION",
      IN_OUT double "EM_EVENTPROBABILITY",
      IN_OUT double "EM_PROBABILITY",
      IN_OUT char(32) "I_TARGET",
      IN_OUT double "P_TARGET0",
      IN_OUT double "P_TARGET1",
      IN_OUT char(4) "_WARN_"
   );
      this."Eyes"= "Eyes";
      this."Support"= "Support";
      this."x_axis_deg_s"= "x_axis_deg_s";
      this."x_axis_g"= "x_axis_g";
      this."y_axis_deg_s"= "y_axis_deg_s";
      this."y_axis_g"= "y_axis_g";
      this."z_axis_deg_s"= "z_axis_deg_s";
      this."z_axis_g"= "z_axis_g";
 
      _DNGOB3MOZDU4DFX9F9860I81W.scoreRecord();
      post_DNGOB3MOZDU4DFX9F9860I81W();
 
      "EM_CLASSIFICATION"= this."EM_CLASSIFICATION";
      "EM_EVENTPROBABILITY"= this."EM_EVENTPROBABILITY";
      "EM_PROBABILITY"= this."EM_PROBABILITY";
      "I_TARGET"= this."I_TARGET";
      "P_TARGET0"= this."P_TARGET0";
      "P_TARGET1"= this."P_TARGET1";
      "_WARN_"= this."_WARN_";
   end;
 
endpackage;
