/*----------------------------------------------------------------------------------*/
/* Product:            Visual Data Mining and Machine Learning                      */
/* Release Version:    V2021.1.2                                                    */
/* Component Version:  V2021.1.2                                                    */
/* CAS Version:        V.04.00M0P06132021                                           */
/* SAS Version:        V.04.00M0P061321                                             */
/* Site Number:        70180938                                                     */
/* Host:               sas-cas-server-default-client                                */
/* Encoding:           utf-8                                                        */
/* Java Encoding:      UTF8                                                         */
/* Locale:             en_US                                                        */
/* Project GUID:       8115ab89-2136-4c59-9e02-82d598192156                         */
/* Node GUID:          329e1f6a-836b-41ce-a32b-cd50f8be7e39                         */
/* Node Id:            2ZVPHRAR0JTTBVVZ14WZNSY0P                                    */
/* Algorithm:          Forest                                                       */
/* Generated by:       Frederik.Vandenberghe@sas.com                                */
/* Date:               02JUL2021:08:23:25                                           */
/*----------------------------------------------------------------------------------*/
package MS_329e1f6a836b41cea32bcd50f8be7e39_02JUL2021082324785 / overwrite=yes;
   dcl package score _2ZVPHRAR0JTTBVVZ14WZNSY0P();
   dcl double "AGE";
   dcl double "BILL_AMT1";
   dcl double "BILL_AMT2";
   dcl double "BILL_AMT3";
   dcl double "BILL_AMT4";
   dcl double "BILL_AMT5";
   dcl double "BILL_AMT6";
   dcl double "LIMIT_BAL";
   dcl double "PAY_AMT1";
   dcl double "PAY_AMT2";
   dcl double "PAY_AMT3";
   dcl double "PAY_AMT4";
   dcl double "PAY_AMT5";
   dcl double "PAY_AMT6";
   dcl double "SEX";
   dcl double "EDUCATION";
   dcl double "MARRIAGE";
   dcl double "PAY_0";
   dcl double "PAY_2";
   dcl double "PAY_3";
   dcl double "PAY_4";
   dcl double "PAY_5";
   dcl double "PAY_6";
   dcl double "default_next_month";
   dcl double "P_default_next_month1" having label n'Predicted: default_next_month=1';
   dcl double "P_default_next_month0" having label n'Predicted: default_next_month=0';
   dcl nchar(32) "I_default_next_month" having label n'Into: default_next_month';
   dcl nchar(4) "_WARN_" having label n'Warnings';
   dcl double "ID";
   dcl double EM_EVENTPROBABILITY;
   dcl nchar(12) EM_CLASSIFICATION;
   dcl double EM_PROBABILITY;
   varlist allvars [_all_];
 
    
   method init();
      _2ZVPHRAR0JTTBVVZ14WZNSY0P.setvars(allvars);
      _2ZVPHRAR0JTTBVVZ14WZNSY0P.setkey(n'8F5EC456E00352C11A6580AB1F9D0C5259B401CD');
      _2ZVPHRAR0JTTBVVZ14WZNSY0P.setOption('_destroyFirstInstLast_', 0);
   end;
    
   method post_2ZVPHRAR0JTTBVVZ14WZNSY0P();
      dcl double _P_;
       
      if "P_DEFAULT_NEXT_MONTH0" = . then "P_DEFAULT_NEXT_MONTH0" = 0.7788;
      if "P_DEFAULT_NEXT_MONTH1" = . then "P_DEFAULT_NEXT_MONTH1" = 0.2212;
      if MISSING("I_DEFAULT_NEXT_MONTH") then do ;
      _P_ = 0.0;
      if "P_DEFAULT_NEXT_MONTH1" > _P_ then do ;
      _P_ = "P_DEFAULT_NEXT_MONTH1";
      "I_DEFAULT_NEXT_MONTH" = '           1';
      end;
      if "P_DEFAULT_NEXT_MONTH0" > _P_ then do ;
      _P_ = "P_DEFAULT_NEXT_MONTH0";
      "I_DEFAULT_NEXT_MONTH" = '           0';
      end;
      end;
      EM_EVENTPROBABILITY = "P_DEFAULT_NEXT_MONTH1";
      EM_CLASSIFICATION = "I_DEFAULT_NEXT_MONTH";
      EM_PROBABILITY = MAX("P_DEFAULT_NEXT_MONTH1", "P_DEFAULT_NEXT_MONTH0");
    
   end;
    
 
   method score(
      double "AGE",
      double "BILL_AMT1",
      double "BILL_AMT2",
      double "BILL_AMT3",
      double "BILL_AMT4",
      double "BILL_AMT5",
      double "BILL_AMT6",
      double "EDUCATION",
      double "ID",
      double "LIMIT_BAL",
      double "MARRIAGE",
      double "PAY_0",
      double "PAY_2",
      double "PAY_3",
      double "PAY_4",
      double "PAY_5",
      double "PAY_6",
      double "PAY_AMT1",
      double "PAY_AMT2",
      double "PAY_AMT3",
      double "PAY_AMT4",
      double "PAY_AMT5",
      double "PAY_AMT6",
      double "SEX",
      IN_OUT char(12) "EM_CLASSIFICATION",
      IN_OUT double "EM_EVENTPROBABILITY",
      IN_OUT double "EM_PROBABILITY",
      IN_OUT char(32) "I_default_next_month",
      IN_OUT double "P_default_next_month0",
      IN_OUT double "P_default_next_month1",
      IN_OUT double "_P_",
      IN_OUT char(4) "_WARN_"
   );
      this."AGE"= "AGE";
      this."BILL_AMT1"= "BILL_AMT1";
      this."BILL_AMT2"= "BILL_AMT2";
      this."BILL_AMT3"= "BILL_AMT3";
      this."BILL_AMT4"= "BILL_AMT4";
      this."BILL_AMT5"= "BILL_AMT5";
      this."BILL_AMT6"= "BILL_AMT6";
      this."EDUCATION"= "EDUCATION";
      this."ID"= "ID";
      this."LIMIT_BAL"= "LIMIT_BAL";
      this."MARRIAGE"= "MARRIAGE";
      this."PAY_0"= "PAY_0";
      this."PAY_2"= "PAY_2";
      this."PAY_3"= "PAY_3";
      this."PAY_4"= "PAY_4";
      this."PAY_5"= "PAY_5";
      this."PAY_6"= "PAY_6";
      this."PAY_AMT1"= "PAY_AMT1";
      this."PAY_AMT2"= "PAY_AMT2";
      this."PAY_AMT3"= "PAY_AMT3";
      this."PAY_AMT4"= "PAY_AMT4";
      this."PAY_AMT5"= "PAY_AMT5";
      this."PAY_AMT6"= "PAY_AMT6";
      this."SEX"= "SEX";
 
      _2ZVPHRAR0JTTBVVZ14WZNSY0P.scoreRecord();
      post_2ZVPHRAR0JTTBVVZ14WZNSY0P();
 
      "EM_CLASSIFICATION"= this."EM_CLASSIFICATION";
      "EM_EVENTPROBABILITY"= this."EM_EVENTPROBABILITY";
      "EM_PROBABILITY"= this."EM_PROBABILITY";
      "I_default_next_month"= this."I_default_next_month";
      "P_default_next_month0"= this."P_default_next_month0";
      "P_default_next_month1"= this."P_default_next_month1";
      "_P_"= this."_P_";
      "_WARN_"= this."_WARN_";
   end;
 
 
   method predictedscore(
      double "AGE",
      double "BILL_AMT1",
      double "BILL_AMT2",
      double "BILL_AMT3",
      double "BILL_AMT4",
      double "BILL_AMT5",
      double "BILL_AMT6",
      double "EDUCATION",
      double "ID",
      double "LIMIT_BAL",
      double "MARRIAGE",
      double "PAY_0",
      double "PAY_2",
      double "PAY_3",
      double "PAY_4",
      double "PAY_5",
      double "PAY_6",
      double "PAY_AMT1",
      double "PAY_AMT2",
      double "PAY_AMT3",
      double "PAY_AMT4",
      double "PAY_AMT5",
      double "PAY_AMT6",
      double "SEX",
      IN_OUT char(12) "EM_CLASSIFICATION",
      IN_OUT double "EM_EVENTPROBABILITY",
      IN_OUT double "EM_PROBABILITY",
      IN_OUT char(32) "I_default_next_month",
      IN_OUT double "P_default_next_month0",
      IN_OUT double "P_default_next_month1",
      IN_OUT char(4) "_WARN_"
   );
      this."AGE"= "AGE";
      this."BILL_AMT1"= "BILL_AMT1";
      this."BILL_AMT2"= "BILL_AMT2";
      this."BILL_AMT3"= "BILL_AMT3";
      this."BILL_AMT4"= "BILL_AMT4";
      this."BILL_AMT5"= "BILL_AMT5";
      this."BILL_AMT6"= "BILL_AMT6";
      this."EDUCATION"= "EDUCATION";
      this."ID"= "ID";
      this."LIMIT_BAL"= "LIMIT_BAL";
      this."MARRIAGE"= "MARRIAGE";
      this."PAY_0"= "PAY_0";
      this."PAY_2"= "PAY_2";
      this."PAY_3"= "PAY_3";
      this."PAY_4"= "PAY_4";
      this."PAY_5"= "PAY_5";
      this."PAY_6"= "PAY_6";
      this."PAY_AMT1"= "PAY_AMT1";
      this."PAY_AMT2"= "PAY_AMT2";
      this."PAY_AMT3"= "PAY_AMT3";
      this."PAY_AMT4"= "PAY_AMT4";
      this."PAY_AMT5"= "PAY_AMT5";
      this."PAY_AMT6"= "PAY_AMT6";
      this."SEX"= "SEX";
 
      _2ZVPHRAR0JTTBVVZ14WZNSY0P.scoreRecord();
      post_2ZVPHRAR0JTTBVVZ14WZNSY0P();
 
      "EM_CLASSIFICATION"= this."EM_CLASSIFICATION";
      "EM_EVENTPROBABILITY"= this."EM_EVENTPROBABILITY";
      "EM_PROBABILITY"= this."EM_PROBABILITY";
      "I_default_next_month"= this."I_default_next_month";
      "P_default_next_month0"= this."P_default_next_month0";
      "P_default_next_month1"= this."P_default_next_month1";
      "_WARN_"= this."_WARN_";
   end;
 
endpackage;
