/*----------------------------------------------------------------------------------*/
/* Product:            Visual Data Mining and Machine Learning                      */
/* Release Version:    V2021.1.2                                                    */
/* Component Version:  V2021.1.2                                                    */
/* CAS Version:        V.04.00M0P06132021                                           */
/* SAS Version:        V.04.00M0P061321                                             */
/* Site Number:        70180938                                                     */
/* Host:               sas-cas-server-default-client                                */
/* Encoding:           utf-8                                                        */
/* Java Encoding:      UTF8                                                         */
/* Locale:             en_US                                                        */
/* Project GUID:       14fb1692-fc82-4817-bd71-08dcaac02f77                         */
/* Node GUID:          c351f01f-b2b6-48e0-a82c-0f8d686ff9ec                         */
/* Node Id:            BKA6YPX79V1KNPOM4E3OGUOZ0                                    */
/* Algorithm:          Linear Regression                                            */
/* Generated by:       Frederik.Vandenberghe@sas.com                                */
/* Date:               01JUL2021:19:09:21                                           */
/*----------------------------------------------------------------------------------*/
package MS_c351f01fb2b648e0a82c0f8d686ff9ec_01JUL2021190921203 / overwrite=yes;
   dcl double "P_BlueBookPrice" having label n'Predicted: BlueBookPrice';
   dcl nchar(17) "VIN";
   dcl double "EM_PREDICTION";
   varlist allvars [_all_];
 
   method _BKA6YPX79V1KNPOM4E3OGUOZ0();
      dcl double _J_;
      dcl double _I_;
      dcl double _TEMP_;
      dcl double _LINP_;
      dcl double _BADVAL_;
      dcl nchar(17) _VIN_;
      dcl double _BETA_46956035_0_[15];
      dcl double _XROW_46956035_0_[15];
       
      _BETA_46956035_0_:=(7999.99999999998, 0, 0, 72000, 4000.00000000001,
      1.8189894035458E-11, 27000, 0, -2999.99999999998, 0, 20000, 4000.00000000002,
      0, 32000, 0);
      _BADVAL_ = 0.0;
      _LINP_ = 0.0;
      _TEMP_ = 0.0;
      _I_ = 0.0;
      _J_ = 0.0;
      _VIN_ = LEFT(TRIM(put(VIN, $17.)));
      do _I_ = 1.0 to 15.0;
      _XROW_46956035_0_[_I_] = 0.0;
      end;
      _XROW_46956035_0_[1.0] = 1.0;
      _TEMP_ = 1.0;
      select (_VIN_);
      when ('12345678901234560') _XROW_46956035_0_[2.0] = _TEMP_;
      when ('12345678901234561') _XROW_46956035_0_[3.0] = _TEMP_;
      when ('12345678901234562') _XROW_46956035_0_[4.0] = _TEMP_;
      when ('12345678901234563') _XROW_46956035_0_[5.0] = _TEMP_;
      when ('12345678901234564') _XROW_46956035_0_[6.0] = _TEMP_;
      when ('12345678901234565') _XROW_46956035_0_[7.0] = _TEMP_;
      when ('12345678901234566') _XROW_46956035_0_[8.0] = _TEMP_;
      when ('12345678901234567') _XROW_46956035_0_[9.0] = _TEMP_;
      when ('12345678901234568') _XROW_46956035_0_[10.0] = _TEMP_;
      when ('12345678901234569') _XROW_46956035_0_[11.0] = _TEMP_;
      when ('12345678901234571') _XROW_46956035_0_[12.0] = _TEMP_;
      when ('12345678901234572') _XROW_46956035_0_[13.0] = _TEMP_;
      when ('12345678901234573') _XROW_46956035_0_[14.0] = _TEMP_;
      when ('12345678901234574') _XROW_46956035_0_[15.0] = _TEMP_;
      otherwise do ;
      _BADVAL_ = 1.0;
      goto SKIP_46956035_0;
      end;
      end;
      do _I_ = 1.0 to 15.0;
      _LINP_ + _XROW_46956035_0_[_I_] * _BETA_46956035_0_[_I_];
      end;
      SKIP_46956035_0: if (_BADVAL_ = 0.0) & ^MISSING(_LINP_) then do ;
      P_BLUEBOOKPRICE = _LINP_;
      end;
      else do ;
      _LINP_ = .;
      P_BLUEBOOKPRICE = .;
      end;
      if "P_BLUEBOOKPRICE" = . then "P_BLUEBOOKPRICE" = 22142.857143;
      EM_PREDICTION = "P_BLUEBOOKPRICE";
    
   end;
    
 
   method score(
      char(17) "VIN",
      IN_OUT double "EM_PREDICTION",
      IN_OUT double "P_BlueBookPrice"
   );
      this."VIN"= "VIN";
 
      _BKA6YPX79V1KNPOM4E3OGUOZ0();
 
      "EM_PREDICTION"= this."EM_PREDICTION";
      "P_BlueBookPrice"= this."P_BlueBookPrice";
   end;
 
 
   method predictedscore(
      char(17) "VIN",
      IN_OUT double "EM_PREDICTION",
      IN_OUT double "P_BlueBookPrice"
   );
      this."VIN"= "VIN";
 
      _BKA6YPX79V1KNPOM4E3OGUOZ0();
 
      "EM_PREDICTION"= this."EM_PREDICTION";
      "P_BlueBookPrice"= this."P_BlueBookPrice";
   end;
 
endpackage;
